// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlr7chddFMRo62zQSFkRMlDjrh5MTG_Sw',
    appId: '1:250990989099:web:f6614036554751bba97f6e',
    messagingSenderId: '250990989099',
    projectId: 'pushnotification-c77cc',
    authDomain: 'pushnotification-c77cc.firebaseapp.com',
    storageBucket: 'pushnotification-c77cc.firebasestorage.app',
    measurementId: 'G-PFKG5DXC8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6DExgWtf3kPFEhmnuJKennj_MgelpzmU',
    appId: '1:250990989099:android:21eae67d8f75c64da97f6e',
    messagingSenderId: '250990989099',
    projectId: 'pushnotification-c77cc',
    storageBucket: 'pushnotification-c77cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOUhokNDndjrRRBcNMfeelbNQ2hj5qtGg',
    appId: '1:250990989099:ios:baa4063a00f3edcaa97f6e',
    messagingSenderId: '250990989099',
    projectId: 'pushnotification-c77cc',
    storageBucket: 'pushnotification-c77cc.firebasestorage.app',
    iosBundleId: 'com.example.quoteapi',
  );
}
